services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  command-service:
    build: ./command-service
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/write_db?sslmode=disable
    depends_on:
      - db

  query-service:
    build: ./query-service
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/write_db?sslmode=disable
    depends_on:
      - db

  consumer-service:
    build: ./consumer-service
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/write_db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
